motion:
  -2 : BREAK
  -1 : STOP
#  0 : .
  1 : Walking Init
  2 : OK
  3 : No
  4 : Thank you
  15 : Sit downn
  16 : Stand up
# soccer
  80 : Init pose
  122 : Get up(Front)
  123 : Get up(Back)
  121 : Right Kick
  120 : Left Kick
  94 : Ceremony
  201 : Foot play
  202 : Roll back
  126 : Push up
# action demo
  90 : Action Demo
motion_shortcut:
# motion_index : button id (0 ~ 9)
  -1 : 0
  81 : 1
  82 : 2
  83 : 3
  84 : 4
